import {
  afterAll,
  afterEach,
  beforeAll,
  beforeEach,
  describe,
  expect,
  it,
  vi,
} from "vitest";
import { POST } from "@app/api/scheduler/tick/route";
import { runAcceptedContinuationSession } from "@/lib/agent/planner";
import { prisma } from "@/lib/db";
import { createPlannedTrip } from "@/lib/trips/create-trip";
import { ensureTestDatabase } from "./test-db";

const sendTelegramMock = vi.hoisted(() => vi.fn());
const sendEmailMock = vi.hoisted(() => vi.fn());

vi.mock("@/lib/notifications/telegram", () => ({
  sendTelegram: sendTelegramMock,
}));

vi.mock("@/lib/notifications/email", () => ({
  sendEmail: sendEmailMock,
}));

vi.mock("@/lib/agent/planner", async () => {
  const actual =
    await vi.importActual<typeof import("@/lib/agent/planner")>(
      "@/lib/agent/planner"
    );

  return {
    ...actual,
    runAcceptedContinuationSession: vi.fn(async (sessionId: string) => {
      const [{ prisma: db }, { replaceTripRoute }] = await Promise.all([
        import("@/lib/db"),
        import("@/lib/trips/route-updates"),
      ]);
      const session = await db.agentSession.findUniqueOrThrow({
        where: { id: sessionId },
      });
      const trip = await db.trip.findFirstOrThrow({
        where: { id: session.tripId ?? undefined, userId: session.userId },
        include: {
          legs: {
            orderBy: { order: "asc" },
            include: { selectedCandidate: true },
          },
        },
      });
      const currentLeg = trip.legs[0];
      const currentLatestDepartAt =
        currentLeg.latestDepartAt ?? new Date(Date.now() + 30 * 60_000);
      const changedLatestDepartAt = new Date(
        currentLatestDepartAt.getTime() + 10 * 60_000
      );
      const changedTargetArriveAt = new Date(
        changedLatestDepartAt.getTime() + 40 * 60_000
      );

      await replaceTripRoute({
        tripId: trip.id,
        userId: session.userId,
        title: "Updated Home-Office",
        finalStopName: "Office",
        targetArriveAt: changedTargetArriveAt,
        stops: [
          {
            order: 1,
            name: "Office",
            lngLat: "121.2,29.2",
            kind: "destination",
            targetArriveAt: changedTargetArriveAt,
          },
        ],
        legs: [
          {
            order: 1,
            originName: "Updated Home",
            originLngLat: "121.1,29.1",
            destinationName: "Office",
            destinationLngLat: "121.2,29.2",
            routeMinutes: 35,
            bufferMinutes: 5,
            totalMinutes: 40,
            latestDepartAt: changedLatestDepartAt,
            mode: "transit",
            routeTitle: "Updated transit route",
            routeRationale: "Traffic is heavier than before.",
            segmentTitle: "Updated segment",
            segmentDetail: "Generated by route recheck.",
            bufferComponents: [
              {
                category: "transfer",
                label: "Transfer",
                minutes: 5,
                reason: "Leave time for transfer.",
              },
            ],
          },
        ],
      });

      const completed = await db.agentSession.update({
        where: { id: sessionId },
        data: {
          status: "completed",
          tripId: trip.id,
          messages: {
            create: {
              role: "assistant",
              content: "Route recheck found a significant route change.",
            },
          },
        },
      });

      return {
        sessionId,
        status: "completed" as const,
        tripId: completed.tripId,
      };
    }),
  };
});

describe("RUS-014 route recheck with significant change", () => {
  const secret = "rus-014-secret";
  let savedSchedulerSecret: string | undefined;

  beforeAll(async () => {
    await ensureTestDatabase();
  });

  beforeEach(() => {
    savedSchedulerSecret = process.env.SCHEDULER_TICK_SECRET;
    process.env.SCHEDULER_TICK_SECRET = secret;
    sendTelegramMock.mockReset();
    sendEmailMock.mockReset();
    sendTelegramMock.mockResolvedValue({
      status: "sent",
      recipient: "telegram-rus-014",
    });
    sendEmailMock.mockResolvedValue({
      status: "sent",
      recipient: "rus-014@example.com",
    });
    vi.mocked(runAcceptedContinuationSession).mockClear();
  });

  afterEach(() => {
    if (savedSchedulerSecret === undefined) {
      delete process.env.SCHEDULER_TICK_SECRET;
    } else {
      process.env.SCHEDULER_TICK_SECRET = savedSchedulerSecret;
    }
  });

  afterAll(async () => {
    await prisma.$disconnect();
  });

  it("processes an authorized due recheck, refreshes future reminders, and sends route-change notifications", async () => {
    const uniqueId = `${Date.now()}-${Math.random().toString(36).slice(2)}`;
    const user = await prisma.user.create({
      data: {
        email: `rus-014-${uniqueId}@example.com`,
        name: "RUS-014 User",
        passwordHash: "hash",
        settings: {
          create: {
            originName: "Home",
            originLngLat: "121.1,29.1",
            routeChangeThresholdMinutes: 3,
            telegramChatId: `telegram-rus-014-${uniqueId}`,
            emailRecipient: "rus-014@example.com",
          },
        },
      },
    });
    const session = await prisma.agentSession.create({
      data: {
        userId: user.id,
        status: "completed",
        prompt: "Plan a commute whose route will significantly change.",
      },
    });
    const now = new Date();
    const latestDepartAt = new Date(now.getTime() + 30 * 60_000);
    const trip = await createPlannedTrip({
      userId: user.id,
      agentSessionId: session.id,
      rawPrompt: "Plan a commute whose route will significantly change.",
      timezone: "Asia/Shanghai",
      title: "Home-Office",
      finalStopName: "Office",
      targetArriveAt: new Date(latestDepartAt.getTime() + 30 * 60_000),
      stops: [
        {
          order: 1,
          name: "Office",
          lngLat: "121.2,29.2",
          kind: "destination",
        },
      ],
      legs: [
        {
          order: 1,
          originName: "Home",
          originLngLat: "121.1,29.1",
          destinationName: "Office",
          destinationLngLat: "121.2,29.2",
          routeMinutes: 25,
          bufferMinutes: 5,
          totalMinutes: 30,
          latestDepartAt,
          bufferComponents: [
            {
              category: "transfer",
              label: "Transfer",
              minutes: 5,
              reason: "Leave time for transfer.",
            },
          ],
        },
      ],
    });
    await prisma.agentSession.update({
      where: { id: session.id },
      data: { tripId: trip.id },
    });

    const leg = await prisma.tripLeg.findFirstOrThrow({
      where: { tripId: trip.id },
      include: { selectedCandidate: true },
    });
    const recheckJob = await prisma.reminderJob.findFirstOrThrow({
      where: { tripId: trip.id, legId: leg.id, kind: "recheck" },
      orderBy: { scheduledFor: "asc" },
    });
    await prisma.reminderJob.update({
      where: { id: recheckJob.id },
      data: { scheduledFor: new Date(Date.now() - 1_000) },
    });

    const response = await POST(
      new Request("http://localhost/api/scheduler/tick", {
        method: "POST",
        headers: { authorization: `Bearer ${secret}` },
      })
    );

    expect(response.status).toBe(200);
    const body = (await response.json()) as {
      processed: number;
      skipped: number;
      sent: number;
      failed: number;
    };
    expect(body.processed).toBeGreaterThanOrEqual(1);
    expect(body.sent).toBeGreaterThanOrEqual(1);
    expect(body.failed).toBe(0);
    expect(runAcceptedContinuationSession).toHaveBeenCalledWith(
      session.id,
      undefined
    );

    await expect(
      prisma.reminderJob.findUniqueOrThrow({ where: { id: recheckJob.id } })
    ).resolves.toMatchObject({
      status: "sent",
      attempts: 1,
    });

    const changedLeg = await prisma.tripLeg.findFirstOrThrow({
      where: { tripId: trip.id, order: leg.order },
      include: { selectedCandidate: true },
    });
    expect(changedLeg.id).not.toBe(leg.id);
    expect(changedLeg.selectedCandidate?.totalMinutes).toBe(40);
    expect(changedLeg.latestDepartAt?.getTime()).toBeGreaterThan(
      (leg.latestDepartAt?.getTime() ?? 0) + 3 * 60_000
    );

    await expect(
      prisma.recalculationLog.findFirstOrThrow({
        where: {
          tripId: trip.id,
          trigger: "recheck",
        },
      })
    ).resolves.toMatchObject({
      status: "sent",
    });

    const refreshedReminders = await prisma.reminderJob.findMany({
      where: { tripId: trip.id, status: "scheduled" },
      orderBy: { scheduledFor: "asc" },
    });
    const changedLatestDepartAt = changedLeg.latestDepartAt;
    expect(changedLatestDepartAt).toBeTruthy();
    expect(refreshedReminders.map((job) => job.scheduledFor.toISOString())).toEqual([
      new Date(changedLatestDepartAt!.getTime() - 30 * 60_000).toISOString(),
      new Date(changedLatestDepartAt!.getTime() - 20 * 60_000).toISOString(),
      new Date(changedLatestDepartAt!.getTime() - 15 * 60_000).toISOString(),
      new Date(changedLatestDepartAt!.getTime() - 10 * 60_000).toISOString(),
      new Date(changedLatestDepartAt!.getTime() - 5 * 60_000).toISOString(),
      changedLatestDepartAt!.toISOString(),
    ]);

    const notifications = await prisma.notificationLog.findMany({
      where: { tripId: trip.id, dedupeKey: { contains: ":route_change:" } },
      orderBy: { channel: "asc" },
    });
    expect(notifications.map((log) => log.channel)).toEqual([
      "email",
      "telegram",
    ]);
    expect(notifications.map((log) => log.status)).toEqual(["sent", "sent"]);
    expect(notifications.every((log) => log.legId === changedLeg.id)).toBe(true);
    expect(sendTelegramMock).toHaveBeenCalledWith(
      expect.objectContaining({
        chatId: `telegram-rus-014-${uniqueId}`,
        text: expect.stringContaining("时间已变化"),
      })
    );
    expect(sendEmailMock).toHaveBeenCalledWith(
      expect.objectContaining({
        to: "rus-014@example.com",
        subject: "通勤时间已变化：Updated Home-Office",
        text: expect.stringContaining("出发时间已更新"),
        html: expect.stringContaining("出发时间已更新"),
      })
    );
    const routeChangeEmail = sendEmailMock.mock.calls[0][0];
    const expectedBeijingDeparture = new Intl.DateTimeFormat("zh-CN", {
      timeZone: "Asia/Shanghai",
      hour: "2-digit",
      minute: "2-digit",
    }).format(changedLatestDepartAt!);
    expect(routeChangeEmail.text).toContain(expectedBeijingDeparture);
    expect(routeChangeEmail.html).toContain(expectedBeijingDeparture);
    expect(routeChangeEmail.text).toContain("Updated transit route");
  });
});
